configuration: Release
image: Visual Studio 2017

install: 
- ps: >-
    Write-Host "Commit being built = " -NoNewLine
    Write-Host $Env:APPVEYOR_REPO_COMMIT -ForegroundColor "Green"
    Write-Host "Current build version = " -NoNewLine
    Write-Host $Env:VERSION -ForegroundColor "Green"
    Write-Host "Target branch = " -NoNewLine
    Write-Host $Env:APPVEYOR_REPO_BRANCH -ForegroundColor "Green"
    Write-Host "Is a Pull Request = " -NoNewLine
    Write-Host $($Env:APPVEYOR_PULL_REQUEST_NUMBER -ne $null) -ForegroundColor "Green"
    $BuildDate = (Get-Date).ToUniversalTime().ToString("yyyyMMddHHmmss")
    Write-Host "Build UTC date = " -NoNewLine
    Write-Host $BuildDate -ForegroundColor "Green"
    $VersionSuffix = ""
    If ($Env:APPVEYOR_REPO_BRANCH -ne "master")
    {
      $VersionSuffix = "-pre$BuildDate"
    }
    $Version = "$($Env:VERSION)$($VersionSuffix)"
    $Env:ASSEMBLY_INFORMATIONAL_VERSION = $Version
    Write-Host "Assembly informational version = " -NoNewLine
    Write-Host $Env:ASSEMBLY_INFORMATIONAL_VERSION -ForegroundColor "Green"
    $Env:SHOULD_PUBLISH_COVERITY_ANALYSIS = $($Env:APPVEYOR_SCHEDULED_BUILD -eq $True)
    Write-Host "Should publish Coverity analysis = " -NoNewLine
    Write-Host $Env:SHOULD_PUBLISH_COVERITY_ANALYSIS -ForegroundColor "Green"

- cmd: set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin;%PATH%

before_build:
- nuget restore ".\Popcorn.sln"

build_script:
- ps: >-
    & cov-build.exe --dir cov-int msbuild "$Env:APPVEYOR_BUILD_FOLDER\Popcorn.sln" `
          /verbosity:normal `
          /p:Configuration=Release `
          /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" `
          /property:ExtraDefine="LEAKS_IDENTIFYING"

test_script:
- ps: >-
    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe "-targetargs:""Popcorn.Tests\bin\$env:CONFIGURATION\Popcorn.Tests.dll""" -filter:"+[Popcorn*]*" -output:opencoverCoverage.xml

    $coveralls = (Resolve-Path "packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()
    
    $env:APPVEYOR_BUILD_NUMBER
    
    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor

after_test:
- ps: >-
    & nuget install PublishCoverity -Version 0.11.0 -ExcludeVersion -OutputDirectory .\packages

    & .\packages\PublishCoverity\PublishCoverity.exe compress `
      -i "$Env:APPVEYOR_BUILD_FOLDER\cov-int" `
      -o "$Env:APPVEYOR_BUILD_FOLDER\$Env:APPVEYOR_PROJECT_NAME.zip"

    & .\packages\PublishCoverity\PublishCoverity.exe publish `
      -t "$Env:coverity_token" `
      -r "$Env:APPVEYOR_REPO_NAME" `
      -z "$Env:APPVEYOR_BUILD_FOLDER\$env:APPVEYOR_PROJECT_NAME.zip" `
      -d "CI server scheduled build." `
      --codeVersion "$Env:ASSEMBLY_INFORMATIONAL_VERSION" `
      --nologo