configuration: Release
image: Visual Studio 2017

install: 
- cmd: set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin;%PATH%

before_build:
- nuget restore ".\Popcorn.sln"

build:
  project: .\Popcorn.sln
  verbosity: minimal

test_script:
- ps: >-
    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:nunit3-console.exe "-targetargs:""Popcorn.Tests\bin\$env:CONFIGURATION\Popcorn.Tests.dll""" -filter:"+[Popcorn*]*" -output:opencoverCoverage.xml

    $coveralls = (Resolve-Path "packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()
    
    $env:APPVEYOR_BUILD_NUMBER
    
    & $coveralls --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --useRelativePaths --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor

after_test:
- ps: >-
    cov-build.exe --dir cov-int msbuild ".\Popcorn.sln" `
          /verbosity:minimal `
          /p:Configuration=Debug `
          /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    & nuget install PublishCoverity -Version 0.11.0 -ExcludeVersion -OutputDirectory .\packages

    & .\packages\PublishCoverity\PublishCoverity.exe compress `
      -i ".\cov-int" `
      -o ".\$Env:APPVEYOR_PROJECT_NAME.zip"

    & .\packages\PublishCoverity\PublishCoverity.exe publish `
      -t "$Env:coverity_token" `
      -r "$Env:APPVEYOR_REPO_NAME" `
      -z ".\$env:APPVEYOR_PROJECT_NAME.zip" `
      -d "CI server scheduled build." `
      --codeVersion "$Env:ASSEMBLY_INFORMATIONAL_VERSION" `
      --nologo